version: "3.3"
services:
  artipie:
    image: artipie/artipie:latest
    container_name: artipie
    restart: unless-stopped
    environment:
      - ARTIPIE_USER_NAME=artipie
      - ARTIPIE_USER_PASS=artipie
    networks:
      - artipie-net
    ports:
      - "8081:8080"
    volumes:
      # change /usr/local/artipie to any convenient location, this is the config folder
      - /usr/local/artipie:/var/artipie/repo
  front:
    image: artipie/front:latest
    container_name: front
    restart: unless-stopped
    networks:
      - artipie-net
    environment:
      - ARTIPIE_USER_NAME=artipie
      - ARTIPIE_USER_PASS=artipie
      - TKN_KEY=abc123
    volumes:
      # change /usr/local/artipie to any convenient location, this is the config folder
      - /usr/local/artipie:/var/artipie/repo
    ports:
      - "8080:8080"

networks:
  artipie-net:
    driver: bridge