name: "Proof: binary repository example works"
"on": [push, pull_request]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2
      - name: Start artipie with binary example configuration
        run: |
          cd examples/binary
          docker run -d -it -v $(pwd)/artipie.yaml:/etc/artipie.yml -v $(pwd):/var/artipie -p 8080:80 artipie/artipie:0.8.9
          # wait for a container to start
          sleep 5
      - name: Check if file upload/download works correctly
        run: |
          echo "hello world" >> text.txt
          curl --silent -X PUT --data-binary "@text.txt" http://localhost:8080/repo/text.txt
          STATUSCODE=$(curl --silent --output /dev/stderr --write-out "%{http_code}" -X GET http://localhost:8080/repo/text.txt)
          if test $STATUSCODE -ne 200; then
            exit 1
          fi

