name: Publish Docker
on:
  create:
    tags:
      - .*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: artipie/artipie
          username: artipie
          password: ${{ secrets.DOCKER_PASSWORD }}
          cache: true
          tag_names: true
