name: Docker Release
on:
  create:
    tags:
      - .*
  push:
    branches:
      - .*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish Image to Docker Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: ${{ secrets.DOCKERHUB_REPO }}
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          cache: true
          tag_names: true
