name: Prepare Artipie for perftest
concurrency: perftest_env
on:
  push:
    tags:
      - "t*"
      - "v*"

jobs:
  perf-test1:
    runs-on: [wsl-server]
    steps:
      - uses: actions/checkout@v3
      - run: cat /etc/issue; mount; ls -lah; env; pwd
      - name: Check variables
        run: test ! -f $HOME/.benchvars && exit 1;exit 0
      - name: Prepare docker env
        run: |
          docker info
          docker stop artipie || :
          docker rm -fv artipie || :
          docker image rm -f artipie/artipie:1.0-SNAPSHOT || :
          docker ps
      - name: Maven build
        run: timeout 600 mvn clean install
      - name: Check docker image
        run: docker image inspect artipie/artipie:1.0-SNAPSHOT|head -n50
      - name: Checkout results repo/branch
        run: git clone --depth=1 https://github.com/chgen/benchmarks.git
      - name: Branch + Artipie server
        run: |
          pwd; ls -lah; git branch -a
          git fetch
          git checkout master
          git pull --ff-only
          cd loadtests
          ./artipie-snapshot.sh 8081
          docker ps
          tree ./root
          ls -lah root/var/repo/artipie
        working-directory: benchmarks
