name: Artipie perftest part n.2
on:
  workflow_run:
    workflows: [ Do performance testing for artipie ]
    types: [ completed ]
#    branches: [ech-dev]
    
jobs:
  perf-test2:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: [wsl-client]
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - run: git branch
      - run: env
        name: 1st step of stage2
      - name: 2nd step of stage2
        run: env; ls -la; pwd; env > /tmp/perftest2.log; ls -lah >> /tmp/perftest2.log; date>>/tmp/perftest2.log; git show --summary HEAD >> /tmp/perftest2.log; git tag --points-at HEAD >>  /tmp/perftest2.log;
      - name: Check variables
        run: test ! -f $HOME/.benchvars && exit 1;exit 0
      - name: Check connection
        run: . "$HOME/.benchvars" && curl -v "http://$TARGET_HOST:$TARGET_PORT/chgen/bintest"

