name: Production deploy
on:
  workflow_run:
    workflows: ["Do performance testing for artipie"]
    types:
      - completed
jobs:
if: ${{ github.event.workflow_run.conclusion == 'success' }}
  perf-test1:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v3
        name: 1st step of stage2
        run: env; ls -la; pwd

